package com.Lino.colorTheory.teams;

import org.bukkit.Material;
import java.util.HashSet;
import java.util.Set;

public class GreenTeamMaterials {
    public static Set<Material> getMaterials() {
        Set<Material> materials = new HashSet<>();

        materials.add(Material.GREEN_WOOL);
        materials.add(Material.GREEN_CONCRETE);
        materials.add(Material.GREEN_CONCRETE_POWDER);
        materials.add(Material.GREEN_TERRACOTTA);
        materials.add(Material.GREEN_GLAZED_TERRACOTTA);
        materials.add(Material.GREEN_STAINED_GLASS);
        materials.add(Material.GREEN_STAINED_GLASS_PANE);
        materials.add(Material.GREEN_CARPET);
        materials.add(Material.GREEN_BED);
        materials.add(Material.GREEN_BANNER);
        materials.add(Material.GREEN_SHULKER_BOX);
        materials.add(Material.GREEN_CANDLE);
        materials.add(Material.GREEN_DYE);

        materials.add(Material.LIME_WOOL);
        materials.add(Material.LIME_CONCRETE);
        materials.add(Material.LIME_CONCRETE_POWDER);
        materials.add(Material.LIME_TERRACOTTA);
        materials.add(Material.LIME_GLAZED_TERRACOTTA);
        materials.add(Material.LIME_STAINED_GLASS);
        materials.add(Material.LIME_STAINED_GLASS_PANE);
        materials.add(Material.LIME_CARPET);
        materials.add(Material.LIME_BED);
        materials.add(Material.LIME_BANNER);
        materials.add(Material.LIME_SHULKER_BOX);
        materials.add(Material.LIME_CANDLE);
        materials.add(Material.LIME_DYE);

        materials.add(Material.EMERALD);
        materials.add(Material.EMERALD_BLOCK);
        materials.add(Material.EMERALD_ORE);
        materials.add(Material.DEEPSLATE_EMERALD_ORE);

        materials.add(Material.GRASS_BLOCK);
        materials.add(Material.GRASS);
        materials.add(Material.TALL_GRASS);
        materials.add(Material.SHORT_GRASS);
        materials.add(Material.MOSS_BLOCK);
        materials.add(Material.MOSS_CARPET);
        materials.add(Material.MYCELIUM);

        materials.add(Material.OAK_LEAVES);
        materials.add(Material.SPRUCE_LEAVES);
        materials.add(Material.BIRCH_LEAVES);
        materials.add(Material.JUNGLE_LEAVES);
        materials.add(Material.ACACIA_LEAVES);
        materials.add(Material.DARK_OAK_LEAVES);
        materials.add(Material.MANGROVE_LEAVES);
        materials.add(Material.CHERRY_LEAVES);
        materials.add(Material.AZALEA_LEAVES);
        materials.add(Material.FLOWERING_AZALEA_LEAVES);

        materials.add(Material.OAK_SAPLING);
        materials.add(Material.SPRUCE_SAPLING);
        materials.add(Material.BIRCH_SAPLING);
        materials.add(Material.JUNGLE_SAPLING);
        materials.add(Material.ACACIA_SAPLING);
        materials.add(Material.DARK_OAK_SAPLING);
        materials.add(Material.MANGROVE_PROPAGULE);
        materials.add(Material.CHERRY_SAPLING);
        materials.add(Material.AZALEA);
        materials.add(Material.FLOWERING_AZALEA);

        materials.add(Material.OAK_LOG);
        materials.add(Material.SPRUCE_LOG);
        materials.add(Material.JUNGLE_LOG);
        materials.add(Material.OAK_WOOD);
        materials.add(Material.SPRUCE_WOOD);
        materials.add(Material.JUNGLE_WOOD);
        materials.add(Material.STRIPPED_OAK_LOG);
        materials.add(Material.STRIPPED_SPRUCE_LOG);
        materials.add(Material.STRIPPED_JUNGLE_LOG);
        materials.add(Material.STRIPPED_OAK_WOOD);
        materials.add(Material.STRIPPED_SPRUCE_WOOD);
        materials.add(Material.STRIPPED_JUNGLE_WOOD);
        materials.add(Material.OAK_PLANKS);
        materials.add(Material.SPRUCE_PLANKS);
        materials.add(Material.JUNGLE_PLANKS);
        materials.add(Material.OAK_SLAB);
        materials.add(Material.SPRUCE_SLAB);
        materials.add(Material.JUNGLE_SLAB);
        materials.add(Material.OAK_STAIRS);
        materials.add(Material.SPRUCE_STAIRS);
        materials.add(Material.JUNGLE_STAIRS);
        materials.add(Material.OAK_FENCE);
        materials.add(Material.SPRUCE_FENCE);
        materials.add(Material.JUNGLE_FENCE);
        materials.add(Material.OAK_FENCE_GATE);
        materials.add(Material.SPRUCE_FENCE_GATE);
        materials.add(Material.JUNGLE_FENCE_GATE);
        materials.add(Material.OAK_DOOR);
        materials.add(Material.SPRUCE_DOOR);
        materials.add(Material.JUNGLE_DOOR);
        materials.add(Material.OAK_TRAPDOOR);
        materials.add(Material.SPRUCE_TRAPDOOR);
        materials.add(Material.JUNGLE_TRAPDOOR);
        materials.add(Material.OAK_SIGN);
        materials.add(Material.SPRUCE_SIGN);
        materials.add(Material.JUNGLE_SIGN);
        materials.add(Material.OAK_HANGING_SIGN);
        materials.add(Material.SPRUCE_HANGING_SIGN);
        materials.add(Material.JUNGLE_HANGING_SIGN);
        materials.add(Material.OAK_BUTTON);
        materials.add(Material.SPRUCE_BUTTON);
        materials.add(Material.JUNGLE_BUTTON);
        materials.add(Material.OAK_PRESSURE_PLATE);
        materials.add(Material.SPRUCE_PRESSURE_PLATE);
        materials.add(Material.JUNGLE_PRESSURE_PLATE);
        materials.add(Material.OAK_BOAT);
        materials.add(Material.SPRUCE_BOAT);
        materials.add(Material.JUNGLE_BOAT);
        materials.add(Material.OAK_CHEST_BOAT);
        materials.add(Material.SPRUCE_CHEST_BOAT);
        materials.add(Material.JUNGLE_CHEST_BOAT);

        materials.add(Material.CACTUS);
        materials.add(Material.SUGAR_CANE);
        materials.add(Material.BAMBOO);
        materials.add(Material.BAMBOO_SAPLING);
        materials.add(Material.KELP);
        materials.add(Material.KELP_PLANT);
        materials.add(Material.DRIED_KELP);
        materials.add(Material.DRIED_KELP_BLOCK);
        materials.add(Material.SEAGRASS);
        materials.add(Material.TALL_SEAGRASS);
        materials.add(Material.SEA_PICKLE);
        materials.add(Material.LILY_PAD);
        materials.add(Material.VINE);
        materials.add(Material.GLOW_LICHEN);
        materials.add(Material.HANGING_ROOTS);
        materials.add(Material.BIG_DRIPLEAF);
        materials.add(Material.SMALL_DRIPLEAF);
        materials.add(Material.DRIPLEAF_STEM);
        materials.add(Material.CAVE_VINES);
        materials.add(Material.CAVE_VINES_PLANT);
        materials.add(Material.SPORE_BLOSSOM);
        materials.add(Material.FERN);
        materials.add(Material.LARGE_FERN);

        materials.add(Material.SLIME_BALL);
        materials.add(Material.SLIME_BLOCK);
        materials.add(Material.SLIME_SPAWN_EGG);

        materials.add(Material.EXPERIENCE_BOTTLE);
        materials.add(Material.EXPERIENCE_ORB);

        materials.add(Material.TURTLE_EGG);
        materials.add(Material.SCUTE);
        materials.add(Material.TURTLE_HELMET);
        materials.add(Material.TURTLE_SPAWN_EGG);

        materials.add(Material.CREEPER_HEAD);
        materials.add(Material.CREEPER_WALL_HEAD);
        materials.add(Material.CREEPER_BANNER_PATTERN);
        materials.add(Material.CREEPER_SPAWN_EGG);

        materials.add(Material.ZOMBIE_HEAD);
        materials.add(Material.ZOMBIE_WALL_HEAD);
        materials.add(Material.ZOMBIE_SPAWN_EGG);
        materials.add(Material.ZOMBIE_VILLAGER_SPAWN_EGG);
        materials.add(Material.HUSK_SPAWN_EGG);
        materials.add(Material.DROWNED_SPAWN_EGG);
        materials.add(Material.ZOMBIFIED_PIGLIN_SPAWN_EGG);

        materials.add(Material.MELON);
        materials.add(Material.MELON_SLICE);
        materials.add(Material.MELON_SEEDS);
        materials.add(Material.GLISTERING_MELON_SLICE);
        materials.add(Material.PUMPKIN_STEM);
        materials.add(Material.ATTACHED_PUMPKIN_STEM);
        materials.add(Material.MELON_STEM);
        materials.add(Material.ATTACHED_MELON_STEM);

        materials.add(Material.WHEAT);
        materials.add(Material.WHEAT_SEEDS);
        materials.add(Material.BEETROOT_SEEDS);
        materials.add(Material.POTATO);
        materials.add(Material.POISONOUS_POTATO);
        materials.add(Material.CARROT);
        materials.add(Material.GOLDEN_CARROT);
        materials.add(Material.APPLE);
        materials.add(Material.GOLDEN_APPLE);
        materials.add(Material.ENCHANTED_GOLDEN_APPLE);

        materials.add(Material.DANDELION);
        materials.add(Material.POPPY);
        materials.add(Material.BLUE_ORCHID);
        materials.add(Material.ALLIUM);
        materials.add(Material.AZURE_BLUET);
        materials.add(Material.RED_TULIP);
        materials.add(Material.ORANGE_TULIP);
        materials.add(Material.WHITE_TULIP);
        materials.add(Material.PINK_TULIP);
        materials.add(Material.OXEYE_DAISY);
        materials.add(Material.CORNFLOWER);
        materials.add(Material.LILY_OF_THE_VALLEY);
        materials.add(Material.WITHER_ROSE);
        materials.add(Material.SUNFLOWER);
        materials.add(Material.LILAC);
        materials.add(Material.ROSE_BUSH);
        materials.add(Material.PEONY);
        materials.add(Material.PITCHER_PLANT);
        materials.add(Material.PITCHER_POD);
        materials.add(Material.TORCHFLOWER);
        materials.add(Material.TORCHFLOWER_SEEDS);
        materials.add(Material.PINK_PETALS);

        materials.add(Material.PARROT_SPAWN_EGG);
        materials.add(Material.OCELOT_SPAWN_EGG);
        materials.add(Material.CAT_SPAWN_EGG);
        materials.add(Material.FROG_SPAWN_EGG);
        materials.add(Material.TADPOLE_SPAWN_EGG);
        materials.add(Material.PANDA_SPAWN_EGG);
        materials.add(Material.VILLAGER_SPAWN_EGG);
        materials.add(Material.WANDERING_TRADER_SPAWN_EGG);
        materials.add(Material.WITCH_SPAWN_EGG);
        materials.add(Material.SILVERFISH_SPAWN_EGG);
        materials.add(Material.GUARDIAN_SPAWN_EGG);
        materials.add(Material.ELDER_GUARDIAN_SPAWN_EGG);

        materials.add(Material.GLOW_BERRIES);
        materials.add(Material.SWEET_BERRIES);
        materials.add(Material.SWEET_BERRY_BUSH);
        materials.add(Material.COCOA);
        materials.add(Material.COCOA_BEANS);

        materials.add(Material.VERDANT_FROGLIGHT);
        materials.add(Material.FROGSPAWN);
        materials.add(Material.TADPOLE_BUCKET);

        materials.add(Material.WARPED_FUNGUS);
        materials.add(Material.WARPED_ROOTS);
        materials.add(Material.WARPED_NYLIUM);
        materials.add(Material.WARPED_WART_BLOCK);
        materials.add(Material.CRIMSON_FUNGUS);
        materials.add(Material.CRIMSON_ROOTS);
        materials.add(Material.CRIMSON_NYLIUM);
        materials.add(Material.WEEPING_VINES);
        materials.add(Material.WEEPING_VINES_PLANT);
        materials.add(Material.TWISTING_VINES);
        materials.add(Material.TWISTING_VINES_PLANT);
        materials.add(Material.NETHER_SPROUTS);
        materials.add(Material.NETHER_WART);
        materials.add(Material.NETHER_WART_BLOCK);

        materials.add(Material.END_PORTAL_FRAME);
        materials.add(Material.ENDER_EYE);
        materials.add(Material.ENDER_PEARL);

        materials.add(Material.BOOK);
        materials.add(Material.WRITABLE_BOOK);
        materials.add(Material.WRITTEN_BOOK);
        materials.add(Material.ENCHANTED_BOOK);
        materials.add(Material.BOOKSHELF);
        materials.add(Material.LECTERN);

        materials.add(Material.CHEST);
        materials.add(Material.TRAPPED_CHEST);
        materials.add(Material.ENDER_CHEST);
        materials.add(Material.BARREL);
        materials.add(Material.CRAFTING_TABLE);
        materials.add(Material.CARTOGRAPHY_TABLE);
        materials.add(Material.FLETCHING_TABLE);
        materials.add(Material.SMITHING_TABLE);
        materials.add(Material.LOOM);
        materials.add(Material.COMPOSTER);
        materials.add(Material.SMOKER);
        materials.add(Material.BLAST_FURNACE);
        materials.add(Material.FURNACE);

        materials.add(Material.HAY_BLOCK);
        materials.add(Material.TARGET);
        materials.add(Material.SCAFFOLDING);
        materials.add(Material.LADDER);
        materials.add(Material.PISTON);
        materials.add(Material.STICKY_PISTON);
        materials.add(Material.OBSERVER);
        materials.add(Material.NOTE_BLOCK);
        materials.add(Material.JUKEBOX);

        materials.add(Material.WEATHERED_COPPER);
        materials.add(Material.WEATHERED_CUT_COPPER);
        materials.add(Material.WEATHERED_CUT_COPPER_SLAB);
        materials.add(Material.WEATHERED_CUT_COPPER_STAIRS);
        materials.add(Material.WEATHERED_CHISELED_COPPER);
        materials.add(Material.WEATHERED_COPPER_DOOR);
        materials.add(Material.WEATHERED_COPPER_TRAPDOOR);
        materials.add(Material.WEATHERED_COPPER_GRATE);
        materials.add(Material.WEATHERED_COPPER_BULB);
        materials.add(Material.WAXED_WEATHERED_COPPER);
        materials.add(Material.WAXED_WEATHERED_CUT_COPPER);
        materials.add(Material.WAXED_WEATHERED_CUT_COPPER_SLAB);
        materials.add(Material.WAXED_WEATHERED_CUT_COPPER_STAIRS);
        materials.add(Material.WAXED_WEATHERED_CHISELED_COPPER);
        materials.add(Material.WAXED_WEATHERED_COPPER_DOOR);
        materials.add(Material.WAXED_WEATHERED_COPPER_TRAPDOOR);
        materials.add(Material.WAXED_WEATHERED_COPPER_GRATE);
        materials.add(Material.WAXED_WEATHERED_COPPER_BULB);

        materials.add(Material.BRAIN_CORAL);
        materials.add(Material.BRAIN_CORAL_BLOCK);
        materials.add(Material.BRAIN_CORAL_FAN);
        materials.add(Material.BRAIN_CORAL_WALL_FAN);
        materials.add(Material.DEAD_BRAIN_CORAL);
        materials.add(Material.DEAD_BRAIN_CORAL_BLOCK);
        materials.add(Material.DEAD_BRAIN_CORAL_FAN);
        materials.add(Material.DEAD_BRAIN_CORAL_WALL_FAN);

        materials.add(Material.POTTED_DANDELION);
        materials.add(Material.POTTED_POPPY);
        materials.add(Material.POTTED_BLUE_ORCHID);
        materials.add(Material.POTTED_ALLIUM);
        materials.add(Material.POTTED_AZURE_BLUET);
        materials.add(Material.POTTED_RED_TULIP);
        materials.add(Material.POTTED_ORANGE_TULIP);
        materials.add(Material.POTTED_WHITE_TULIP);
        materials.add(Material.POTTED_PINK_TULIP);
        materials.add(Material.POTTED_OXEYE_DAISY);
        materials.add(Material.POTTED_CORNFLOWER);
        materials.add(Material.POTTED_LILY_OF_THE_VALLEY);
        materials.add(Material.POTTED_WITHER_ROSE);
        materials.add(Material.POTTED_OAK_SAPLING);
        materials.add(Material.POTTED_SPRUCE_SAPLING);
        materials.add(Material.POTTED_BIRCH_SAPLING);
        materials.add(Material.POTTED_JUNGLE_SAPLING);
        materials.add(Material.POTTED_ACACIA_SAPLING);
        materials.add(Material.POTTED_DARK_OAK_SAPLING);
        materials.add(Material.POTTED_MANGROVE_PROPAGULE);
        materials.add(Material.POTTED_CHERRY_SAPLING);
        materials.add(Material.POTTED_AZALEA);
        materials.add(Material.POTTED_FLOWERING_AZALEA);
        materials.add(Material.POTTED_FERN);
        materials.add(Material.POTTED_CACTUS);
        materials.add(Material.POTTED_BAMBOO);
        materials.add(Material.POTTED_CRIMSON_FUNGUS);
        materials.add(Material.POTTED_WARPED_FUNGUS);
        materials.add(Material.POTTED_CRIMSON_ROOTS);
        materials.add(Material.POTTED_WARPED_ROOTS);
        materials.add(Material.POTTED_RED_MUSHROOM);
        materials.add(Material.POTTED_BROWN_MUSHROOM);
        materials.add(Material.POTTED_DEAD_BUSH);

        return materials;
    }
}